baseurl = "http://blog.johnboyd.io/"
languageCode = "en-us"
title = "blog.johnboyd.io"
theme = "er"
author = "John Boyd IV"
copyright = "© 2018, John Boyd IV. All rights reserved."
canonifyurls = true
paginate = 10
publishDir = "docs"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  googleAnalytics = "UA-103090041-2"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 4
    url = "/contact/"
  [[menu.main]]
    name = "Github"
    pre = "<i class='fa fa-id-card-o fa-fw'></i>"
    weight = 5
    url = "https://github.com/phreaknik/"